"""add_user_pipelines_table

Revision ID: 3fd3558a7f8b
Revises: 8d2e3d869a4a
Create Date: 2026-03-12 17:11:39.417747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3fd3558a7f8b'
down_revision: Union[str, None] = '8d2e3d869a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
