"""add_onboarding_completed_to_users

Revision ID: 8d2e3d869a4a
Revises: 8b96ad078c03
Create Date: 2026-03-12 15:35:44.314612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d2e3d869a4a'
down_revision: Union[str, None] = '8b96ad078c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    # ### end Alembic commands ###
