"""add claude_session_id and claude_authenticated

Revision ID: c419eaa35d76
Revises: 
Create Date: 2026-03-06 18:43:00.151984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c419eaa35d76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('claude_session_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('claude_authenticated', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'claude_authenticated')
    op.drop_column('chat_sessions', 'claude_session_id')
    # ### end Alembic commands ###
